version: '3'

services:
  telecalling-service:
    build: ./telecalling-service
    command: node coreServer.js
    volumes:
     - ./telecalling-service:/VoiceAmity/telecalling-service
    ports:
      - "5000:5000"
  admin-web-server:
    build: ./Admin-web-server
    command: node coreServer.js
    volumes:
     - ./Admin-web-server:/VoiceAmity/Admin-web-server
    ports:
      - "5001:3000"